routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::namespace('Admin')->prefix('admins')->group(function () {
    Route::get('login', 'LoginController@getLogin')->name('admin.getLogin');
    Route::post('login', 'LoginController@Login')->name('admin.login');
    Route::get('logout', 'LoginController@logout')->name('admin.logout');
});


Route::namespace('Admin')->prefix('admins')->middleware('checklogin::class')->group(function () {
    Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');

    Route::resource('category', 'CategoryController');

    Route::resource('product', 'ProductController')->except(['show']);
    Route::get('product/search', 'ProductController@search')->name('product.search');

    Route::resource('role', 'RoleController')->except(['show']);

    Route::resource('permission', 'PermissionController')->except(['show', 'edit']);

    Route::resource('user', 'UserController');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ProductRequest;
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index()
    {
        $products = Product::orderBy('id', 'DESC')->paginate(3);

        return view('admin.product.index', [
            'products' => $products,
        ]);
    }

    public function store(ProductRequest $request)
    {
        $input = $request->all();
        if ($request->hasFile('image')) {
            $input['image'] = time() . '.' . $request->image->getClientOriginalName();
            $request->image->move(public_path('admin/images'), $input['image']);
        } else {
            $input['image'] = "image";
        }
        Product::create($input);
        $products = Product::orderBy('id', 'DESC')->paginate(3);

        return view('admin.product.table_product', [
            'products' => $products,
        ]);
    }

    public function edit($id)
    {
        $product = Product::find($id);

        return view('admin.product.modal_product', [
            'product' => $product,
        ]);
    }

    public function update(Request $request, $id)
    {
        $input = $request->all();
        $product = Product::find($id);

        if ($request->hasFile('image')) {
            if ($product->image != $request->image->getClientOriginalName()) {
                unlink('admin/images/' . $product->image);
            }
            $input['image'] = time() . '.' . $request->image->getClientOriginalName();
            $request->image->move(public_path('admin/images'), $input['image']);
        }

        $product->update($input);
        $products = Product::orderBy('id', 'DESC')->paginate(3);

        return view('admin.product.table_product', [
            'products' => $products,
        ]);
    }

    public function destroy($id)
    {
        $product = Product::findOrFail($id);

        if ($product->image) {
            unlink('admin/images/' . $product->image);
        }
        $product->delete();
        $products = Product::orderBy('id', 'DESC')->paginate(3);

        return view('admin.product.table_product', [
            'products' => $products,
        ]);
    }

    public function search(Request $request)
    {
        $keyword = $request->get('keyword');
        if ($keyword) {
            $products = Product::where('name', 'LIKE', "%$keyword%")->orderBy('id', 'DESC')->paginate(3);
            return view('admin.product.table_product', [
                'products' => $products,
            ]);
        }
    }
}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\Api\CreateProductRequest;
use App\Http\Requests\Api\UpdateProductRequest;
use App\Http\Resources\ProductCollection;
use App\Product;
use App\Http\Controllers\Controller;
use App\Http\Resources\Product as ProductResource;

class ProductController extends Controller
{
    public function index()
    {
        $products = Product::all();
        return new ProductCollection($products);
    }

    public function store(CreateProductRequest $request)
    {
        $product = Product::create($request->all());
        return response()->json([
            'status_code' => 200,
            'message' => 'Thêm thành công',
            'data' => $product,
        ]);
    }

    public function show($id)
    {
        $product = Product::findOrFail($id);
        return response()->json([
            'status_code' => 200,
            'message' => 'Hiển thị 1 sản phẩm',
            'data' => new ProductResource($product),
        ]);
    }

    public function update(UpdateProductRequest $request, $id)
    {
        $product = Product::findOrFail($id);
        $product->update($request->all());
        return response()->json([
            'status_code' => 200,
            'message' => 'Cập nhập thành công',
            'data' => $product
        ]);
    }

    public function destroy($id)
    {
        Product::findOrFail($id)->delete();
        return response()->json([
            'status_code' => 200,
            'message' => 'Xóa thành công',
            'data' => true,
        ]);
    }
}

resources/views/admin/product/index.blade.php
@extends('admin.layout.master')
@section('title','product')
@section('content')
    <div class="row my-3">
        <h3 class="col-3">Product</h3>
        <div class="col-3" id="modal">
            <!-- Button modal create-->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal_create">
                Create
            </button>
            <!-- Modal create-->
            <div class="modal fade " id="modal_create" tabindex="-1" aria-hidden="true">
                <div class="modal-dialog modal-xl">
                    <form enctype="multipart/form-data" id="form_create">
                        <div class="modal-content">
                            <div class="modal-body">
                                <div class="container mt-4 mb-5">
                                    <div class="row">
                                        <div class="col-6 form-group">
                                            <div>
                                                <label for="product_name">Name <sup
                                                        class="text-danger">(*)</sup></label>
                                                <input type="text" id="name" name="name" class="form-control" required>
                                            </div>
                                            <div>
                                                <label for="price">Price <sup class="text-danger">(*)</sup></label>
                                                <input type="text" id="price" name="price" class="form-control"
                                                       required>
                                            </div>
                                            <div>
                                                <label for="category">Category <sup
                                                        class="text-danger">(*)</sup></label>
                                                <select id="category_id" name="category_id" class="custom-select"
                                                        required>
                                                    @foreach($categories as $category)
                                                        <option
                                                            value="{{ $category->id }}">{{ $category->name }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-6 form-group">
                                            <div>
                                                <label for="image" class="col-form-label">Image <sup
                                                        class="text-danger">(*)</sup></label>
                                                <div>
                                                    <input type="file" accept="image/*" id="image" name="image" required
                                                           onchange="loadFile(event)" style="display: none;">
                                                    <img height="120" width="120" id="output">
                                                    <label class="form-label" for="image" style="cursor: pointer;">
                                                        <p class="btn btn-outline-success">
                                                            <i class="fa fa-upload"></i>
                                                        </p>
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="description">Description <sup class="text-danger">(*)</sup></label>
                                                <textarea id="description" name="description" class="form-control"
                                                          required rows="3"></textarea>
                                            </div>
                                        </div>
                                        <div>
                                            <p>Note: <i class="text-danger">(*) is a required field</i></p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="modal-footer">
                                <button class="btn btn-primary" type="button" id="btn_create"
                                        data-href="{{ route('product.store') }}">Create
                                </button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-6">
            <form class="form" >
                <input class="form-control" data-href={{ route('product.search') }} type="search" name="search" id="search" placeholder="Search">
            </form>
        </div>
    </div>

    <div id="tbl_result">
        <table class="table table-hover table-responsive-sm table-responsive-md ">
            <thead class="thead">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Image</th>
                <th scope="col">Category</th>
                <th scope="col">Price</th>
                <th scope="col">Description</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($products as $product)
                <tr>
                    <th>{{ $product->id }}</th>
                    <td>{{ $product->name }}</td>
                    <td>
                        <img src="{{ asset('admin/images/'.$product->image) }}" style="width: 80px;height: 80px">
                    </td>
                    <td>{{ $product->category->name }}</td>
                    <td>{{ $product->price }}</td>
                    <td>{{ $product->description }}</td>
                    <td class="d-flex">
                        <button class="btn btn-success mr-2 btn-edit"
                                data-href="{{ route('product.edit',$product->id) }}" data-toggle="modal"> Edit
                        </button>
                        <button class="btn btn-danger btn-del" value="{{ $product->id }}"
                                data-href="{{ route('product.destroy', $product->id) }}"> Del
                        </button>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $products->links() }}
    </div>

@endsection

@section('script')
    <script src="{{ asset('admin/product/js/product.js') }}"></script>
@endsection

resources/views/admin/product/modal_product.blade.php
<!-- Button modal create-->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal_update"> Create</button>
<div class="modal fade " id="modal_update" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <form enctype="multipart/form-data" id="form_update">
            {!! method_field('PUT') !!}
            <div class="modal-content">
                <div class="modal-body">
                    <div class="container mt-4 mb-5">
                        <div class="row">
                            <div class="col-6 form-group">
                                <div>
                                    <label for="product_name">Name <sup class="text-danger">(*)</sup></label>
                                    <input value="{{ $product->name }}" type="text" id="name" name="name"
                                           class="form-control" required>
                                </div>
                                <div>
                                    <label for="price">Price <sup class="text-danger">(*)</sup></label>
                                    <input value="{{ $product->price }}" type="text" id="price" name="price"
                                           class="form-control" required>
                                </div>
                                <div>
                                    <label for="category">Category <sup class="text-danger">(*)</sup></label>
                                    <select id="category_id" name="category_id" class="custom-select" required>
                                        <option
                                            value="{{ $product->category->id }}">{{ $product->category->name }}</option>
                                        @foreach($categories as $category)
                                            @if(!$product->category->id)
                                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-6 form-group">
                                <div>
                                    <label for="image" class="col-form-label">Image <sup
                                            class="text-danger">(*)</sup></label>
                                    <div>
                                        <input type="file" accept="image/*" id="image" name="image" required
                                               onchange="loadFile(event)" style="display: none;">
                                        <img height="120" width="120" id="output"
                                             src="{{ asset('admin/images/'.$product->image) }}">
                                        <label class="form-label" for="image" style="cursor: pointer;">
                                            <p class="btn btn-outline-success">
                                                <i class="fa fa-upload"></i>
                                            </p>
                                        </label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="description">Description<sup class="text-danger">(*)</sup></label>
                                    <textarea id="description" name="description" class="form-control" required
                                              rows="3">{{ $product->description }}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button class="btn btn-primary" type="button" id="btn_update"
                            data-href="{{ route('product.update',$product->id) }}">Update
                    </button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/admin/product/table_product.blade.php
<table class="table table-hover table-responsive-sm table-responsive-md ">
    <thead class="thead">
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Image</th>
        <th scope="col">Category</th>
        <th scope="col">Price</th>
        <th scope="col">Description</th>
        <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    @foreach($products as $product)
        <tr>
            <th>{{ $product->id }}</th>
            <td>{{ $product->name }}</td>
            <td>
                <img src="{{ asset('admin/images/'.$product->image) }}" style="width: 80px;height: 80px">
            </td>
            <td>{{ $product->category->name }}</td>
            <td>{{ $product->price }}</td>
            <td>{{ $product->description }}</td>
            <td class="d-flex">
                <button class="btn btn-success mr-2 btn-edit" data-href="{{ route('product.edit',$product->id) }}" data-toggle="modal" > Edit</button>
                <button class="btn btn-danger btn-del" value="{{ $product->id }}" data-href="{{ route('product.destroy', $product->id) }}"> Del</button>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
{{ $products->links() }}