routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::namespace('Admin')->prefix('admins')->group(function () {
    Route::get('login', 'LoginController@getLogin')->name('admin.getLogin');
    Route::post('login', 'LoginController@Login')->name('admin.login');
    Route::get('logout', 'LoginController@logout')->name('admin.logout');
});


Route::namespace('Admin')->prefix('admins')->middleware('checklogin::class')->group(function () {
    Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');

    Route::resource('category', 'CategoryController');

    Route::resource('product', 'ProductController')->except(['show']);
    Route::get('product/search', 'ProductController@search')->name('product.search');

    Route::resource('role', 'RoleController')->except(['show']);

    Route::resource('permission', 'PermissionController')->except(['show', 'edit']);

    Route::resource('user', 'UserController');
});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $guarded = [];

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\RoleRequest;
use App\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class RoleController extends Controller
{
    public function index()
    {
        $roles = Role::all();

        return view('admin.role.index', [
            'roles' => $roles,
        ]);
    }

    public function store(RoleRequest $request)
    {
        try {
            DB::beginTransaction();
            $input = [
                'name' => $request->input('name'),
            ];
            $permissions = $request->input('checkbox');
            $role = Role::create($input);
            $role->permissions()->attach($permissions);
            DB::commit();

            return back();
        } catch (\Exception $exception) {
            DB::rollBack();
        }
    }

    public function edit($id)
    {
        $list_permissions = DB::table('permission_role')->where('role_id', $id)->pluck('permission_id');
        $role = Role::findOrFail($id);

        return view('admin.role.form_role', [
            'role' => $role,
            'list_permissions' => $list_permissions
        ]);
    }

    public function update(RoleRequest $request, $id)
    {
        try {
            DB::beginTransaction();
            Role::where('id', $id)->update([
                'name' => $request->input('name'),
            ]);
            DB::table('permission_role')->where('role_id', $id)->delete();
            $role = Role::find($id);
            $role->permissions()->attach($request->input('checkbox'));
            DB::commit();

            return back();
        } catch (\Exception $exception) {
            DB::rollBack();
        }
    }


    public function destroy($id)
    {
        try {
            DB::beginTransaction();
            $role = Role::find($id);
            $role->delete();
            $role->permissions()->detach();
            DB::commit();

            return back();
        } catch (\Exception $exception) {
            DB::rollBack();
        }

    }
}

resources/views/admin/role/form_role.blade.php
@extends('admin.layout.master')
@section('title','role')
@section('content')
    <div class="my-3">
        @if ($errors->any())
            <div class="alert alert-danger alert-dismissible" role="alert">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only" style="font-size: 35px">Close</span>
                </button>
            </div>
        @endif
        <form method="POST" action="{{ route('role.update',$role->id) }}">
            @csrf
            {!! @method_field('PUT') !!}
            <div class="modal-body">
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" value="{{ $role->name }}" name="name">
                        </div>
                    </div>
                    <div class="form-group col-6">
                        <p>Permission</p>
                        @foreach($permissions as $permission)
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox"
                                       {{ $list_permissions->contains($permission->id) ? "checked" : "" }} name="checkbox[]"
                                       value="{{ $permission->id }}" class="custom-control-input"
                                       id="permission{{ $permission->id }}">
                                <label class="custom-control-label"
                                       for="permission{{ $permission->id }}">{{ $permission->name }}</label>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Update</button>
                <a href="{{ route('role.index') }}" type="button" class="btn btn-secondary">Back</a>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/role/index.blade.php
@extends('admin.layout.master')
@section('title','role')
@section('content')
    <div>
        <div class="row my-3">
            <div class="col-6">
                <h3>Role</h3>
            </div>
            <div class="col-6">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal"> Create
                </button>
                <!-- Modal -->
                <div class="modal fade" id="modal" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content container">
                            <form method="POST" action="{{ route('role.store') }}">
                                @csrf
                                <div class="modal-body">
                                    <div class="row">
                                        <div class="col-6">
                                            <div class="form-group">
                                                <label for="name">Name</label>
                                                <input type="text" class="form-control" name="name">
                                            </div>
                                        </div>
                                        <div class="form-group col-6">
                                            <p>Permission</p>
                                            @foreach($permissions as $permission)
                                            <div class="custom-control custom-checkbox">
                                                <input type="checkbox" name="checkbox[]" value="{{ $permission->id }}" class="custom-control-input" id="permission{{ $permission->id }}">
                                                <label for="permission{{ $permission->id }}" class="custom-control-label">{{ $permission->name }}</label>
                                            </div>
                                            @endforeach
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @if ($errors->any())
            <div class="alert alert-danger alert-dismissible" role="alert">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only" style="font-size: 35px">Close</span>
                </button>
            </div>
        @endif
        <div>
            <table class="table table-hover table-responsive-sm table-responsive-md ">
                <thead class="thead">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Permission</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($roles as $role)
                    <tr>
                        <th>{{ $role->id }}</th>
                        <td>{{ $role->name }}</td>
                        <td>
                            @foreach($role->permissions as $permission)
                                {{ $permission->name }},
                            @endforeach
                        </td>
                        <td class="d-flex">
                            <!-- Button trigger modal -->
                            <a href="{{ route('role.edit',$role->id) }}" type="button" class="btn btn-success mr-2"> Edit </a>
                            <button data-toggle="modal" data-target="#delete{{ $role->id }}" class="btn btn-danger btn-del"> Del</button>
                            <div class="modal fade" id="delete{{ $role->id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <form action="{{ route('role.destroy',$role->id) }}" method="POST">
                                            {!! @method_field('DELETE') !!}
                                            @csrf
                                            <div class="modal-body">
                                                <h5> Do you want to delete</h5>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="submit" class="btn btn-primary">Delete</button>
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection